### ISSUE TITLE
No backup written to file

### ISSUE THREAD

**Issue by theksi** [Ariphaos/imageretainer#2]
Hello,
Running image retainer on the following platform
- Foundry 10.291
- Pathfinder 4.4.2
- Image retainer V0.1.1
I've noticed , When starting backup image paths macro that no files were written on disk, though the console indicates that the backup is done. (see attached file)
![imeretainer](https://user-images.githubusercontent.com/43031034/210215316-8e12d5cf-3d21-4a77-afe5-b4b6459fd627.png)
Please note that restoring data from a previous backup works fine

**Comment by theksi** [comment]
Please note that I have also tested the module on a starfinder system with the same results ... It smells like a permission issue but can't find any traces

**Comment by Ariphaos** [comment]
Apparently I'm not getting notifications from Github anymore.

I've noticed this and am looking into it.

**Comment by Ariphaos** [comment]
Woo fixxored.
